#!/bin/python

from os import environ as env
import clicommon

# Usage msg
USAGE_MSG = "Usage: list_sizes"
OVERLORD = env['OVERLORD']
ARGS = 0

# Create CLI
cli = clicommon.CLI(
    overlord=OVERLORD,
    usage=USAGE_MSG,
    args_expected=ARGS,
)

# GET
sizes = cli.GET('/cloud/sizes')

# Print sizes
print('-------------------------------------------------------')
print('- Sizes:')
i = 0
for size in sizes:
    print("-- {0}: {1} - {2} - CPUS: {3}, RAM: {4}".format(i, size['name'], size['id'], size['cpus'], size['ram']))
    i = i + 1
print('-------------------------------------------------------')
