#!/bin/python

from os import environ as env
import clicommon

# Usage msg
USAGE_MSG = "Usage: list_applications"
OVERLORD = env['OVERLORD']
TOKEN = env['TOKEN']
ARGS = 0

# Create CLI
cli = clicommon.CLI(
    overlord=OVERLORD,
    token=TOKEN,
    usage=USAGE_MSG,
    args_expected=ARGS,
)

# GET
apps = cli.GET('/applications')

# Print applications
print('-------------------------------------------------------')
print('- Applications:')
i = 0
for app in apps:
    print("-- {0}: {1} - {2}".format(i, app['name'], app['id']))
    i = i + 1
print('-------------------------------------------------------')


