#!/bin/sh

# Print help
echo "======================================================="
echo "Use this command with source or dot (.) command, e.g: source ./login. Otherwise the other commands of the CLI will not work."

# Get token and set environment
export TOKEN=$(python ./_login)
