#!/bin/python

from os import environ as env
import clicommon

# Usage msg
USAGE_MSG = "Usage: login"
OVERLORD = env['OVERLORD']
ARGS = 0

# Create CLI
cli = clicommon.CLI(
    overlord=OVERLORD,
    usage=USAGE_MSG,
    args_expected=ARGS,
)

# GET
login = cli.GET('/cloud/login')

# Print login status
print('-------------------------------------------------------')
print('- Login status: {0}'.format(login))
print('-------------------------------------------------------')
